(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
const STORE='bhs_v5_';
const safe=t=>String(t??'').replace(/[<>&"']/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[m]));
const db={get:k=>JSON.parse(localStorage.getItem(STORE+k)||'null'),set:(k,v)=>localStorage.setItem(STORE+k,JSON.stringify(v))};
function seed(){if(!db.get('users'))db.set('users',[{name:'Administradora',email:'admin@babyhelenashop.cl',pass:'BabyHelena2026',role:'admin'}]);if(!db.get('orders'))db.set('orders',[{code:'BHS1001',email:'cliente@demo.cl',status:'Enviado por Blue Express',track:'BX-123456',progress:3}]);if(!db.get('products'))db.set('products',window.BHS_PRODUCTS||[])}seed();
function drawer(){const d=$('#drawer'),b=$('#menuBtn'),c=$('#closeMenu'),back=$('#drawerBack'); if(!d||!b)return; b.onclick=()=>d.classList.add('open'); [c,back].forEach(x=>x&&(x.onclick=()=>d.classList.remove('open')))}
function renderProducts(){const wrap=$('#productsGrid');if(!wrap)return;const products=db.get('products')||window.BHS_PRODUCTS||[];const cats=['Todo',...new Set(products.map(p=>p.cat))];const tabs=$('#tabs');let active='Todo';function draw(){wrap.innerHTML=products.filter(p=>active==='Todo'||p.cat===active).map(p=>`<article class="card"><div class="photo">${safe(p.emoji)}</div><div class="card-body"><span class="badge">${safe(p.tag)}</span><h3>${safe(p.name)}</h3><p>${safe(p.cat)}</p><div class="price">${money(p.price)}</div><button class="btn pink" data-add="${safe(p.id)}">Agregar</button></div></article>`).join('');$$('[data-add]').forEach(btn=>btn.onclick=()=>addCart(btn.dataset.add));}
if(tabs){tabs.innerHTML=cats.map(c=>`<button class="tab ${c===active?'active':''}" data-cat="${safe(c)}">${safe(c)}</button>`).join('');tabs.onclick=e=>{const btn=e.target.closest('[data-cat]');if(!btn)return;active=btn.dataset.cat;$$('.tab',tabs).forEach(t=>t.classList.toggle('active',t.dataset.cat===active));draw()}}
draw()}
function addCart(id){const products=db.get('products')||[];const p=products.find(x=>x.id===id);if(!p)return;const cart=db.get('cart')||[];cart.push(p);db.set('cart',cart);renderCart();}
function renderCart(){const count=$('#cartCount'),items=$('#cartItems'),total=$('#cartTotal');const cart=db.get('cart')||[];if(count)count.textContent=cart.length;if(items)items.innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><span>${safe(p.name)}</span><strong>${money(p.price)}</strong><button data-remove="${i}">×</button></div>`).join(''):'<p>Tu carrito está vacío.</p>';if(total)total.textContent=money(cart.reduce((s,p)=>s+Number(p.price||0),0));$$('[data-remove]').forEach(b=>b.onclick=()=>{const c=db.get('cart')||[];c.splice(Number(b.dataset.remove),1);db.set('cart',c);renderCart()})}
function cartUI(){const b=$('#cartBtn'),p=$('#cartPanel');if(b&&p)b.onclick=()=>p.classList.toggle('open');renderCart()}
function auth(){const login=$('#loginForm'),reg=$('#registroForm');if(login)login.onsubmit=e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase(),pass=$('#password').value;const u=(db.get('users')||[]).find(x=>x.email.toLowerCase()===email&&x.pass===pass);if(!u)return $('#msg').textContent='Datos incorrectos.';db.set('session',{email:u.email,name:u.name,role:u.role});location.href=u.role==='admin'?'admin/dashboard.html':'perfil.html'};if(reg)reg.onsubmit=e=>{e.preventDefault();const users=db.get('users')||[];const u={name:safe($('#name').value),email:$('#email').value.trim().toLowerCase(),pass:$('#password').value,role:'cliente'};if(users.some(x=>x.email===u.email))return $('#msg').textContent='Ese correo ya existe.';users.push(u);db.set('users',users);db.set('session',{email:u.email,name:u.name,role:'cliente'});location.href='perfil.html'};}
function profile(){const box=$('#profileBox');if(!box)return;const s=db.get('session');if(!s){location.href='login.html';return}const orders=(db.get('orders')||[]).filter(o=>o.email===s.email||s.role==='admin');box.innerHTML=`<h2>Hola, ${safe(s.name)}</h2><p>Desde aquí puedes revisar tus pedidos y datos de cuenta.</p>${orders.map(o=>`<div class="step done"><strong>${safe(o.code)}</strong><br>${safe(o.status)}<br>Seguimiento: ${safe(o.track)}</div>`).join('')||'<p>Aún no tienes pedidos registrados.</p>'}`}
function tracking(){const form=$('#trackForm'),res=$('#trackResult');if(!form)return;form.onsubmit=e=>{e.preventDefault();const q=$('#trackCode').value.trim().toLowerCase();const o=(db.get('orders')||[]).find(x=>x.code.toLowerCase()===q||x.track.toLowerCase()===q);if(!o)return res.innerHTML='<p>No encontramos ese pedido. Revisa el código o escríbenos por WhatsApp.</p>';const steps=['Pedido confirmado','Preparando pedido','Despachado','En camino','Entregado'];res.innerHTML=`<h3>${safe(o.code)}</h3><p>${safe(o.status)} · ${safe(o.track)}</p><div class="timeline">${steps.map((s,i)=>`<div class="step ${i<=o.progress?'done':''}">${i<=o.progress?'✔':'○'} ${s}</div>`).join('')}</div>`}}
function logout(){const b=$('#logoutBtn');if(b)b.onclick=()=>{localStorage.removeItem(STORE+'session');location.href='index.html'}}
window.BHS={db,safe,money};drawer();renderProducts();cartUI();auth();profile();tracking();logout();
})();
