(()=>{'use strict';
const $=(q)=>document.querySelector(q),$$=(q)=>[...document.querySelectorAll(q)];
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP'}).format(n);
const safe=s=>String(s??'').replace(/[<>&"']/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#039;'}[m]));
const db={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function seed(){if(!db.get('bhs_seed',false)){db.set('bhs_seed',true);db.set('bhs_products',window.BHS_PRODUCTS||[]);db.set('bhs_orders',[{code:'BHS1001',email:'cliente@demo.cl',status:'Pedido preparado',carrier:'Blue Express',tracking:'BX123456789CL',steps:['Compra confirmada','Pedido preparado','Enviado a transporte']}]);}}
async function sha256(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const ADMIN_HASH='8d6e93557d99e421d96d28ed2849054b6f53bdc6e96bfbb01749c8afbc1642a3';
function current(){return db.get('bhs_session',null)}
function showSession(){const el=$('#sessionName'); if(el){const u=current(); el.textContent=u?`Hola, ${u.name||u.email}`:'Iniciar sesión';}}
function menu(){const side=$('#sideMenu'),over=$('#overlay');$('#openMenu')?.addEventListener('click',()=>{side.classList.add('open');over.classList.add('show')});$('#closeMenu')?.addEventListener('click',()=>{side.classList.remove('open');over.classList.remove('show')});over?.addEventListener('click',()=>{side.classList.remove('open');over.classList.remove('show')});}
function renderProducts(){const box=$('#productGrid'); if(!box)return; const products=db.get('bhs_products',window.BHS_PRODUCTS||[]); box.innerHTML=products.map(p=>`<article class="product"><div class="product-img">${safe(p.emoji||'🛍️')}</div><span class="tag">${safe(p.tag||p.cat)}</span><h3>${safe(p.name)}</h3><p>${safe(p.cat)}</p><div class="price">${money(Number(p.price||0))}</div><button class="btn primary add" data-id="${safe(p.id)}">Agregar</button></article>`).join(''); $$('.add').forEach(b=>b.onclick=()=>addCart(b.dataset.id));}
function addCart(id){const cart=db.get('bhs_cart',[]);cart.push(id);db.set('bhs_cart',cart);updateCart();alert('Producto agregado al carrito');}
function updateCart(){const el=$('#cartCount'); if(el)el.textContent=db.get('bhs_cart',[]).length;}
function auth(){const login=$('#loginForm'),reg=$('#registerForm');login?.addEventListener('submit',async e=>{e.preventDefault();const email=safe(login.email.value.trim().toLowerCase()), pass=login.password.value; if(email==='admin@babyhelenashop.cl' && await sha256(pass)===ADMIN_HASH){db.set('bhs_session',{email,name:'Administradora',role:'admin'});location.href='admin/dashboard.html';return} const users=db.get('bhs_users',[]);const user=users.find(u=>u.email===email&&u.pass===pass); if(!user){$('#loginMsg').textContent='Datos incorrectos';return} db.set('bhs_session',{email:user.email,name:user.name,role:'client'});location.href='perfil.html';});reg?.addEventListener('submit',e=>{e.preventDefault();const users=db.get('bhs_users',[]),email=safe(reg.email.value.trim().toLowerCase()); if(users.some(u=>u.email===email)){alert('Ese correo ya está registrado');return} users.push({name:safe(reg.name.value),email,pass:reg.password.value});db.set('bhs_users',users);db.set('bhs_session',{email,name:safe(reg.name.value),role:'client'});location.href='perfil.html';});$('#logout')?.addEventListener('click',()=>{localStorage.removeItem('bhs_session');location.href='index.html'});}
function profile(){const box=$('#profileBox'); if(!box)return; const u=current(); if(!u){location.href='login.html';return} const orders=db.get('bhs_orders',[]).filter(o=>o.email===u.email||u.role==='admin'); box.innerHTML=`<h2>Mi perfil</h2><p>${safe(u.name)} · ${safe(u.email)}</p><h3>Mis pedidos</h3>`+orders.map(o=>`<div class="card"><b>${safe(o.code)}</b><p>${safe(o.status)} · ${safe(o.carrier)}</p><p>N° seguimiento: ${safe(o.tracking)}</p></div>`).join('')||'<p>Aún no tienes pedidos registrados.</p>';}
function tracking(){const f=$('#trackingForm'),r=$('#trackingResult'); if(!f)return; f.addEventListener('submit',e=>{e.preventDefault();const q=f.query.value.trim().toLowerCase();const o=db.get('bhs_orders',[]).find(x=>[x.code,x.tracking].some(v=>String(v).toLowerCase()===q));r.innerHTML=o?`<div class="card"><h3>${safe(o.status)}</h3><p>Transporte: ${safe(o.carrier)}</p><p>Código: ${safe(o.tracking)}</p><ol>${o.steps.map(s=>`<li>${safe(s)}</li>`).join('')}</ol></div>`:'<p>No encontramos ese código. Revisa si está bien escrito.</p>';});}
seed();menu();renderProducts();updateCart();auth();profile();tracking();showSession();
})();
