(function(){'use strict';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
const state={cart:JSON.parse(localStorage.getItem('bhs_cart')||'[]')};
function save(){localStorage.setItem('bhs_cart',JSON.stringify(state.cart)); updateCart();}
function updateCart(){const n=state.cart.reduce((a,b)=>a+b.qty,0); $$('.cartCount').forEach(e=>e.textContent=n)}
function productCard(p){return `<article class='product'><div class='prodImg'>${p.emoji}</div><div class='prodInfo'><span class='tag'>${p.tag}</span><h3>${p.name}</h3><p>${p.cat}</p><div class='price'>${money(p.price)}</div><button class='btn' data-add='${p.id}' style='width:100%;margin-top:14px'>Agregar</button></div></article>`}
function renderProducts(limit){const box=$('#productsGrid'); if(!box) return; const data=(window.BHS_PRODUCTS||[]).slice(0,limit||99); box.innerHTML=data.map(productCard).join('');}
function add(id){const p=(window.BHS_PRODUCTS||[]).find(x=>x.id===id); if(!p)return; const item=state.cart.find(x=>x.id===id); if(item)item.qty++; else state.cart.push({id,qty:1,name:p.name,price:p.price}); save(); alert('Producto agregado al carrito');}
function seed(){if(!localStorage.getItem('bhs_orders')){localStorage.setItem('bhs_orders',JSON.stringify([{code:'BHS1001',client:'clienta@demo.cl',carrier:'Blue Express',tracking:'BX123456789CL',status:'En preparación',steps:['Pedido recibido','Pago confirmado','En preparación']}]))}}
function login(email,pass){const users=JSON.parse(localStorage.getItem('bhs_users')||'[]'); const adminHash='QmFieUhlbGVuYTIwMjY='; if(email==='admin@babyhelenashop.cl'&&btoa(pass)===adminHash){localStorage.setItem('bhs_session',JSON.stringify({email,role:'admin'})); location.href='admin/dashboard.html'; return} const u=users.find(x=>x.email===email&&x.pass===btoa(pass)); if(u){localStorage.setItem('bhs_session',JSON.stringify({email,role:'client'})); location.href='perfil.html'} else alert('Datos incorrectos')}
function register(email,pass,name){const users=JSON.parse(localStorage.getItem('bhs_users')||'[]'); if(users.some(x=>x.email===email)) return alert('Este correo ya existe'); users.push({email,pass:btoa(pass),name}); localStorage.setItem('bhs_users',JSON.stringify(users)); alert('Cuenta creada. Ahora inicia sesión.'); location.href='login.html'}
function tracking(){const form=$('#trackingForm'), res=$('#trackingResult'); if(!form) return; form.addEventListener('submit',e=>{e.preventDefault(); const q=$('#trackingInput').value.trim().toUpperCase(); const orders=JSON.parse(localStorage.getItem('bhs_orders')||'[]'); const o=orders.find(x=>x.code.toUpperCase()===q||x.tracking.toUpperCase()===q); res.classList.remove('hidden'); res.innerHTML=o?`<h3>${o.status}</h3><p><b>Pedido:</b> ${o.code}</p><p><b>Transporte:</b> ${o.carrier}</p><p><b>Seguimiento:</b> ${o.tracking}</p><p>${o.steps.map(s=>'✔ '+s).join('<br>')}</p>`:`<h3>No encontrado</h3><p>Revisa el código o escríbenos por WhatsApp.</p>`})}
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]'); if(addBtn)add(addBtn.dataset.add); if(e.target.closest('#openMenu')) $('#drawer')?.classList.add('open'); if(e.target.closest('#closeMenu')||e.target.closest('.drawerMask')) $('#drawer')?.classList.remove('open')});
document.addEventListener('submit',e=>{if(e.target.id==='loginForm'){e.preventDefault(); login($('#email').value.trim(),$('#password').value)} if(e.target.id==='registerForm'){e.preventDefault(); register($('#email').value.trim(),$('#password').value,$('#name').value.trim())}});
seed(); renderProducts(location.pathname.includes('index')||location.pathname.endsWith('/')?4:null); updateCart(); tracking();
})();
